### ISSUE TITLE
Slider position

### ISSUE THREAD

**Issue by OscarCR88** [junkboy0315/react-compare-image#3]
Hi there.
Terrific component you've got here, so simple yet so powerful. I was wondering wether there's a way to know the slider's position at will.
Thank you for your time

**Comment by junkboy0315** [comment]
Hi @OscarCR88 
so you want to know position of the slider at the start(end) of sliding, right?
anyway, PR is welcome!

**Comment by OscarCR88** [comment]
Any particular steps to build the project?

**Comment by OscarCR88** [comment]
Hi there
I'm trying to generate the bundle.js, by running yarn build, but I'm getting an error:
```
E:\...\react-compare-image\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (E:\...\App\react-compare-image\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at E:\...\ App\react-compare-image\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (E:\...\App\react-compare-image\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
```
can you comment on that?
Thank you

**Comment by junkboy0315** [comment]
I think the following may be the cause.
https://github.com/webpack/webpack/issues/8082#issuecomment-424307597

Do you have global installed webpack-cli ?
Or did you upgraded webpack-cli of the project manually ?

**Comment by OscarCR88** [comment]
hmm, nevermind. Anyways, I'm ready to make a PR: I've created a new branch, and provided test code. What would be the next step? Sorry, it's my first contribution

**Comment by junkboy0315** [comment]
standard procedure is as follows:

- fork the repo to your private account
- edit the repo
- make a pull request

https://help.github.com/articles/fork-a-repo/
